### ISSUE TITLE
東京に引っ越すまでにしたい

### ISSUE THREAD

**Issue by tanatana** [tanatana/tanatana#1]
- [x] 寿司善のちらしずし食べたい
- [x] マドラグの卵サンド食べたい
- [ ] miyo's  coffeeのマフィン食べたい
- [ ] はふうのカツサンド食べたい
- [ ] [長楽館といえばアフタヌーンティー](http://www.chourakukan.co.jp/cr/cafe.php#!afternoon_tea)

**Comment by tanatana** [comment]
食べたいしか並んでなくて文化的に貧しい感じがする

**Comment by aibou** [comment]
Should use `- [ ]`

ex)

```
- [ ] Go Sushi-zen
```

**Comment by tanatana** [comment]
@aibou Thanks :)

**Comment by aibou** [comment]
:+1:

**Comment by aibou** [comment]
深夜2:30から築地の寿司屋に並ぶ気力もってませんか？

**Comment by tanatana** [comment]
@aibou 気力あるんで #2 に追加しました
